### ISSUE TITLE
setup instructions

### ISSUE THREAD

**Issue by hhellbusch** [zalando/PGObserver#10]
the set up instructions are a little sparse.

Some additional steps i had to do - 

```
$ easy_install cherrypy 
$ easy_install Jinja2
$ easy_install argparse
```

Some additional things that could be included:
* what version of python is required
* what python dependencies are required
* what versions of postgresql are supported

Additionally the setup requires directly inserting rows into the database. I think it would be worthwhile to make a simple install script to initialize the data.

**Comment by kmoppel** [comment]
Closing the ticket. Readme was enchanced recently to cover required versions.
