### ISSUE TITLE
pgobserver.conf

### ISSUE THREAD

**Issue by andreas42** [zalando/PGObserver#100]
Hi,
I'm trying to install PGObserver. I have cloned the project from git. However, I cannot find the pgobserver.conf file. I'm referring to the third line in the setup guide:
Copy pgobserver.conf to the home folder: ~/.pgobserver.conf

Running find etc on the PGObserver directory didn't return anything useful.

Thanks and best regards,
Andreas

**Comment by jwh5566** [comment]
I can't find this file either. could you resolve the problem.

**Comment by jwh5566** [comment]
I can't find this file either. could you resolve the problem.

**Comment by LappleApple** [comment]
@slitsche @a1exsh Can you please respond to these prospective users? Thanks! cc @Jan-M

**Comment by Jan-M** [comment]
https://github.com/zalando/PGObserver/blob/master/frontend/pgobserver_frontend.example.yaml could be it, .conf sounds like python config thus frontend.

**Comment by LappleApple** [comment]
Hi @andreas42 and @jwh5566, do you need something else here? I'll close the comment, and you can reopen if needed.

**Comment by lupsups** [comment]
Hi, did anyone @andreas42  and @jwh5566 put the file on the home, how did this ended?
