### ISSUE TITLE
Add a top pg_stat_statements section similar to top sprocs to the main screen

### ISSUE THREAD

**Issue by kmoppel** [zalando/PGObserver#32]
Should be also possible to configure if one wants to see it or not.

**Comment by psycho-ir** [comment]
Here is the implementation of this issue:
https://github.com/zalando/PGObserver/pull/44

**Comment by kmoppel** [comment]
hey, thanks for the PR! will review it shortly:)

**Comment by kmoppel** [comment]
@psycho-ir - could you please check the comments on the PR, I encountered some problems :)

**Comment by kmoppel** [comment]
Implemented with https://github.com/zalando/PGObserver/pull/62
