### ISSUE TITLE
Is it possible to add adhoc queries to graphs ?

### ISSUE THREAD

**Issue by davecramer** [zalando/PGObserver#45]

**Comment by sli67** [comment]
Hi,
there is a possibility to gather and show pg_stat_statements data. Might be this is what you were looking for?

**Comment by davecramer** [comment]
This is one thing, yes, but things like measuring lag between machines
would also be nice

Dave Cramer

**Comment by psycho-ir** [comment]
I will add graph feature for statements in next version of PGObserver,
Currently by: https://github.com/zalando/PGObserver/pull/44
It is possible to monitor top statements. I will have implemented graph of calls (you will be able to click on queries and watch its graph of calls for example) in next version by 10 days.
I am a little busy in these days and after solving the issues which are raised by @kmoppel on my pull request i will start it.

Is it what you need?

**Comment by davecramer** [comment]
I think so, although once I started writing what I wanted I realized doing
lag requires querying two servers/databases and doing some math. Not sure
this really solves my problem

Dave Cramer

**Comment by sli67** [comment]
Well, doing math is not in the scope of Pgobserver though it provides the data for doing this. So I'll close this issue.
