### ISSUE TITLE
How to measure Sprocs (stored procedures) ?

### ISSUE THREAD

**Issue by ErikvdVen** [zalando/PGObserver#56]
It's not very clear to me how to measure the sproc statistics.

So far I know I've got these 3 tables:
```
sproc_performance_data
sproc_schemas_monitoring_configuration
sprocs
```
This is my ```sproc_schemas_monitoring_configuration``` table:
![screen shot 2015-11-04 at 15 52 31](https://cloud.githubusercontent.com/assets/5047027/10941683/dc1b2990-830c-11e5-9aac-72368d8839c8.png)

Do I need to insert rows in those other 2 tables? Or should this be enough? Or should the scmc_host_id be equal to the host id in the hosts table, which is monitored?

**Comment by hjacobs** [comment]
Maybe @kmoppel can answer this?

**Comment by kmoppel** [comment]
Thanks for the interest!
The setup on the picture looks good to me. E.g. spocs from "public" and all other schemas besides "te?mp%" would be included. The setup with id=0 applies to all monitored hosts by default and one can override it by providing some different include/exclude names for your given host_id.
No need to insert anything into other tables (besides "hosts") - everything else should be filled automatically with the data from the host being monitored.
LMK if having any other issues on getting going.

**Comment by ErikvdVen** [comment]
Thanks for your response @kmoppel , but I already tried that :(. I already filled the hosts table from the beginning, but sprocs aren't measured. Everything works, but sprocs. Any ideas what might be the problem? Do I need to activate something else?

**Comment by Jan-M** [comment]
Did you enable on PostgreSQL side to actually track performance metrics for stored procedures?

**Comment by kmoppel** [comment]
Yes, this could be it. By default track_functions is not turned. There's a hint about it on the project main page also - see http://www.postgresql.org/docs/current/static/runtime-config-statistics.html#GUC-TRACK-FUNCTIONS for enabling the feature

**Comment by ErikvdVen** [comment]
Sounds good! Thanks! I will test it ASAP and I'll let you know the results :+1:
