### ISSUE TITLE
500 Internal Server Error on /perfstatstatements

### ISSUE THREAD

**Issue by ErikvdVen** [zalando/PGObserver#57]
It seems like the frontend has trouble reading some queries from the ```pg_stat_statements``` table:
```
500 Internal Server Error
...
perf_stat_statements.html, line 84, in block "body"
    <tr class="hiddenrow" style="display:none" ><td colspan="8"><textarea readonly>{{ d['query'] }}</textarea></td>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 210: ordinal not in range(128)
```
This row seems to cause trouble in perf_stat_statements.html:
```
<tr class="hiddenrow" style="display:none" ><td colspan="8"><textarea readonly>{{ d['query'] }}</textarea></td>
```
Same problem with the perf_stat_statements_detailed.html by the way:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 210: ordinal not in range(128)
```

Hopefully you know how to fix it?

**EDIT:**

I guess I found the query which causes the problem:
```
UPDATE afg SET status = status_in, updated_at = now(), display = display_in, urls = urls_in, type = type_in, headline = headline_in, description_1 = description_1_in, description_2 = description_2_in, destination_url = destination (...)
```
Guess the ```(...)``` is the problem? Cause when I delete 
```
<tr class="hiddenrow" style="display:none" ><td colspan="8"><textarea readonly>{{ d['query'] }}</textarea></td>
```
from perf_stat_statements.html, the /perfstatstatements loads fine. And the show graph url loads perfectly fine for all queries, except for the queries which start with 
```
UPDATE afg SET status = status_in, updated_at = now(), 
```
So I guess the ```(...)``` is causing problems.

**Comment by kmoppel** [comment]
Thanks for the report! Could you please try again now? I hope I fixed it with
https://github.com/zalando/PGObserver/commit/f991d5b34675b98f7d5a60a55baa55ad5486ca86

**Comment by ErikvdVen** [comment]
Great! Thank you very much. Works like charm.
