### ISSUE TITLE
Add database column to Performance Analyses views

### ISSUE THREAD

**Issue by rippiedoos** [zalando/PGObserver#69]
At the moment we have multiple databases in one cluster. We have even multiple clusters on one host.

If we want to use the Performance Analyses views we can only select hosts. If you have configured multiple databases on one cluster and one host you have multiple hosts in the selection box but no way to view what database you are actually on. 

It would be really helpful to use the UI Longname or UI Shortname in the menu to view the performance-stuff, in stead off the hostname. That way you can view all the other databases on the same host or cluster as well.

**Comment by kmoppel** [comment]
Ok yes, would make sense. Issue didn't pop up in our environment because we create separate service names (IPs) for every database, even if they're on the same cluster. Will attack it soon:)

**Comment by rippiedoos** [comment]
I figured something like that was the reason for the current setup. I tried to change the templates and code my self to create a pull request, but after looking at it for 2 hours and going over the different parts of the code it was too much work. I thought I would need to change half of the code because everything is referencing a host. And changing that to host_ui_shortname would not only mean changing methods  and templates but also changing queries, api and other parts as well and a lot of testing. 

So we created for every database a hosts-file-entry to make the current setup work. It would still be nice to have this implemented but at the moment we switched to services for databases as well. Kind of. 

Thanks for the reply!

Andreas

**Comment by kmoppel** [comment]
@rippiedoos hi, just and update - there's already a PR waiting (https://github.com/zalando/PGObserver/pull/71) to be reviewed by one of my colleagues :)

**Comment by rippiedoos** [comment]
@kmoppel That's a substantial PR and looks very promissing! I thank you very much for that! I will install it on our system as soon as I have time for it. 

I was heading the same way with my own changes but couldn't get near as close as you did. Also nice to see that you guys react really well to input from others. Thumbs up!!

**Comment by kmoppel** [comment]
Merged. Sorry, merge took some time :) NB! As the commit message says - a schema migration script from "sql/schema_upgrade/02_performance_views_hostname_to_uishortname.sql" is needed for existing installations. Let me know if encountering any problems. Cheers

**Comment by rippiedoos** [comment]
The only problem i'm running into is the constraint on the hosts-table. We used ui_shortnames with underscores in it, what was fine previously. So I changed the constraint to include the _ character and it's running fine now. Thanks for this!
