### ISSUE TITLE
Provide more Documentation for the Frontend

### ISSUE THREAD

**Issue by MALPI** [zalando/PGObserver#8]
Hi there,

I tried to use the tool today.

It was not possible for me, to get it running properly. At least for the python part I was missing documentation, how to get it running... Can you provide me some more Informations?

**Comment by LappleApple** [comment]
Looks like there have been some recent updates on the frontend section of the documentation, but is there a Docker image as per the request? Didn't see any references to one in the README ...

**Comment by kmoppel** [comment]
Dockerfiles are now actually there, both in "frontend" and "backend" folders and for testing purposes there is also a Vagrant setup which utilizes them behind the scenes. Details [here](https://github.com/zalando/PGObserver#quick-test-run-using-vagrant).

And also documentation in general has been improved some months ago so I think we can close this ticket for now.
