### ISSUE TITLE
frontend error 

### ISSUE THREAD

**Issue by rogerioluz** [zalando/PGObserver#9]
Hi!!

I'm trying to start the frontend via run.sh and i get this error

Traceback (most recent call last):
  File "web.py", line 88, in <module>
    main()
  File "web.py", line 76, in main
    root.report = report.Report()
AttributeError: 'NoneType' object has no attribute 'report'

You guys can help?

Thanks!

**Comment by kmoppel** [comment]
Cannot reproduce in the latest version.
