### ISSUE TITLE
configuration problems

### ISSUE THREAD

**Issue by msalzmann** [zalando/PGObserver#95]
Hi there,

I have problems to displayed  all tables with **Top 10 SProcs......**.  On the same page, Load Average 15min Sprocs shows a graph. I have already configured the pg_stat_statement module in my cluster.

`shared_preload_libraries = 'pg_stat_statements'         # (change requires restart)
pg_stat_statements.max = 10000
pg_stat_statements.track = all`

With this enabled, i am able to do a
select * from pg_stat_statement
when connected to my database in psql and get the expected result, but not in PGObserver web frontend.

I get an warning message in pgmon_java_*****

`Nov 24, 2016 2:23:25 PM de.zalando.pgobserver.gatherer.SprocGatherer getSchemasToBeMonitored
WARNING: NOT nspname LIKE ANY (array['public','pg\_%','information_schema','tmp%','temp%']::text[]) AND nspname LIKE ANY (array['%']::text[])
Nov 24, 2016 2:23:25 PM de.zalando.pgobserver.gatherer.SprocGatherer gatherData`

Are there some configurations of postgresql that i am missing?
Could you please give me some more advice.

Thanks 

Matthias

**Comment by slitsche** [comment]
Hello Matthias,

maybe you should specify the schema name patterns you want to be monitored? This is done via the table `sproc_schemas_monitoring_configuration`. This defines the schemas for which stats about sprocs are gathered. Sproc statistics are gathered from `pg_stat_user_functions` not from `pg_stat_statements`.

Regards
Stefan

**Comment by msalzmann** [comment]
Hi Stefan,

Thanks. Sorry for the late Feedback. 
Now it works!! ;-)

Your reference to pgstat_user_functions helped me.

I have realized that I forgot to activated the Statics Collection in the postgresql.conf.

Best regards

Matthias
