### ISSUE TITLE
build problem: some packages cannot be found

### ISSUE THREAD

**Issue by mendris** [zalando/PGObserver#98]
during the build I have some problem: [INFO] 13 errors 
some packages cannot be found!
I have a compilation errors, can someone help me?
tanks

[build.zip](https://github.com/zalando/PGObserver/files/716194/build.zip)

**Comment by mendris** [comment]
I hav e found a solution, file to modify: pom.xml

old value: <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
new value: <url>http://oss.sonatype.org/content/groups/public/</url>

**Comment by LappleApple** [comment]
Hi @mendris: Thanks for your interest in PGObserver. If you use it and feel like sharing your feedback, we'd appreciate it a lot.
